"""Initial complete migration

Revision ID: 28e6a9fa0e8d
Revises: 959ae2b4073d
Create Date: 2025-11-07 12:37:24.707626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e6a9fa0e8d'
down_revision = '959ae2b4073d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_point', sa.String(length=200), nullable=True))
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('drop_point')

    # ### end Alembic commands ###
