"""Initial complete migration

Revision ID: 959ae2b4073d
Revises: 
Create Date: 2025-11-07 10:04:43.330064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959ae2b4073d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('branch_id', name=op.f('pk_branches')),
    sa.UniqueConstraint('branch_name', name=op.f('uq_branches_branch_name'))
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_contact_number', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('current_longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('vehicle_number', name=op.f('uq_vehicles_vehicle_number'))
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('zone_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_zones_branch_id_branches')),
    sa.PrimaryKeyConstraint('zone_id', name=op.f('pk_zones'))
    )
    op.create_table('pickupdroppoints',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('point_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], name=op.f('fk_pickupdroppoints_zone_id_zones')),
    sa.PrimaryKeyConstraint('point_id', name=op.f('pk_pickupdroppoints'))
    )
    op.create_table('pricing_slabs',
    sa.Column('slab_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('min_distance_km', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_distance_km', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('slab_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_pricing_slabs_branch_id_branches')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], name=op.f('fk_pricing_slabs_zone_id_zones')),
    sa.PrimaryKeyConstraint('slab_id', name=op.f('pk_pricing_slabs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('admin', 'subuser', 'parent', 'driver', name='user_role_enum'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('license_info', sa.String(length=100), nullable=True),
    sa.Column('mother_contact_number', sa.String(length=20), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('pickup_point_id', sa.Integer(), nullable=True),
    sa.Column('drop_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_users_branch_id_branches')),
    sa.ForeignKeyConstraint(['drop_point_id'], ['pickupdroppoints.point_id'], name=op.f('fk_users_drop_point_id_pickupdroppoints')),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickupdroppoints.point_id'], name=op.f('fk_users_pickup_point_id_pickupdroppoints')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], name=op.f('fk_users_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('contact_number', name=op.f('uq_users_contact_number')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_alerts_branch_id_branches')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_alerts_sender_user_id_users')),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('pk_alerts'))
    )
    op.create_table('bus_routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('transport_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_bus_routes_branch_id_branches')),
    sa.ForeignKeyConstraint(['transport_supervisor_id'], ['users.id'], name=op.f('fk_bus_routes_transport_supervisor_id_users')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], name=op.f('fk_bus_routes_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('route_id', name=op.f('pk_bus_routes'))
    )
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('rfid_reader_id', sa.String(length=100), nullable=True),
    sa.Column('gps_device_id', sa.String(length=100), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_buses_branch_id_branches')),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_buses_driver_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buses')),
    sa.UniqueConstraint('bus_number', name=op.f('uq_buses_bus_number')),
    sa.UniqueConstraint('gps_device_id', name=op.f('uq_buses_gps_device_id')),
    sa.UniqueConstraint('rfid_reader_id', name=op.f('uq_buses_rfid_reader_id'))
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('admission_no', sa.String(length=50), nullable=False),
    sa.Column('grade_div', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('father_mob_no', sa.String(length=20), nullable=True),
    sa.Column('mother_mob_no', sa.String(length=20), nullable=True),
    sa.Column('zone_area_name', sa.String(length=100), nullable=True),
    sa.Column('pick_up_point', sa.String(length=200), nullable=True),
    sa.Column('same_pickup_as_drop', sa.Boolean(), nullable=True),
    sa.Column('route_no', sa.String(length=50), nullable=True),
    sa.Column('pickup_route_name', sa.String(length=100), nullable=True),
    sa.Column('slab_name', sa.String(length=100), nullable=True),
    sa.Column('slab_amount', sa.Float(), nullable=True),
    sa.Column('rfid_card_uid', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('pickup_point_id', sa.Integer(), nullable=False),
    sa.Column('drop_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], name=op.f('fk_children_branch_id_branches')),
    sa.ForeignKeyConstraint(['drop_point_id'], ['pickupdroppoints.point_id'], name=op.f('fk_children_drop_point_id_pickupdroppoints')),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_children_parent_id_users')),
    sa.ForeignKeyConstraint(['pickup_point_id'], ['pickupdroppoints.point_id'], name=op.f('fk_children_pickup_point_id_pickupdroppoints')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], name=op.f('fk_children_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children')),
    sa.UniqueConstraint('admission_no', name=op.f('uq_children_admission_no')),
    sa.UniqueConstraint('rfid_card_uid', name=op.f('uq_children_rfid_card_uid'))
    )
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_driver_bus_id_buses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_locations_bus_id_buses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('student_bus_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('bus_route_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_timestamp', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['bus_route_id'], ['bus_routes.route_id'], name=op.f('fk_student_bus_logs_bus_route_id_bus_routes')),
    sa.ForeignKeyConstraint(['student_id'], ['children.id'], name=op.f('fk_student_bus_logs_student_id_children')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], name=op.f('fk_student_bus_logs_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_student_bus_logs'))
    )
    op.create_table('user_alerts',
    sa.Column('user_alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name=op.f('fk_user_alerts_alert_id_alerts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_alerts_user_id_users')),
    sa.PrimaryKeyConstraint('user_alert_id', name=op.f('pk_user_alerts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alerts')
    op.drop_table('student_bus_logs')
    op.drop_table('locations')
    op.drop_table('driver')
    op.drop_table('children')
    op.drop_table('buses')
    op.drop_table('bus_routes')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('pricing_slabs')
    op.drop_table('pickupdroppoints')
    op.drop_table('zones')
    op.drop_table('vehicles')
    op.drop_table('branches')
    # ### end Alembic commands ###
