"""Initial complete migration

Revision ID: d3a3fba79fc9
Revises: 28e6a9fa0e8d
Create Date: 2026-01-07 15:28:49.110491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a3fba79fc9'
down_revision = '28e6a9fa0e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pickup_point_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('drop_point_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('drop_point')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_point', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('drop_point_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pickup_point_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('zone_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
